PaGlobal_Window_Stat_All = {
  _ui = {
    _btn_Close = nil,
    _stc_bounusStatBG = nil,
    _stc_line = nil,
    _txt_addDamageTemplate = nil,
    _txt_desc = nil,
    _txt_offence = nil,
    _txt_awakenOffence = nil,
    _txt_shyAwakenOffence = nil,
    _txt_hit = nil,
    _txt_hitRate = nil,
    _txt_dDv = nil,
    _txt_dDvRate = nil,
    _txt_dPv = nil,
    _txt_rDv = nil,
    _txt_rDvRate = nil,
    _txt_rPv = nil,
    _txt_mDv = nil,
    _txt_mDvRate = nil,
    _txt_mPv = nil,
    _txt_reduceRate = nil,
    _txt_characterStat_desc = nil,
    _txt_specialStat_desc = nil,
    _txt_equipStat_desc = nil,
    _txt_hiddenStat_desc = nil,
    _txt_added_desc = nil,
    _txt_bonus_desc = nil,
    _txt_result_desc = nil,
    _txt_addedDDToMonster_title = nil,
    _txt_addedDDToKama_title = nil,
    _txt_addedDDToAin_title = nil,
    _txt_addedDDToHuman_title = nil,
    _txt_addedPVFromMonster_title = nil,
    _txt_resistanceFromMonster_title = nil,
    _txt_StunRegist_title = nil,
    _txt_GrabRegist_title = nil,
    _txt_DownRegist_title = nil,
    _txt_AirRegist_title = nil,
    _txt_characterStat = {},
    _txt_specialStat = {},
    _txt_equipStat = {},
    _txt_hiddenStat = {},
    _txt_added = {},
    _txt_bonus = {},
    _txt_result = {},
    _txt_addedDDToMonster = nil,
    _txt_addedDDToKama = nil,
    _txt_addedDDToAin = nil,
    _txt_addedDDToHuman = nil,
    _txt_addedPVFromMonster = nil,
    _txt_resistanceFromMonster = nil,
    _txt_StunRegist = nil,
    _txt_GrabRegist = nil,
    _txt_DownRegist = nil,
    _txt_AirRegist = nil,
    _txt_consoleKeyGuide = nil
  },
  _ATTACK_TYPE = {
    _DISTANCE = 0,
    _RANGE = 1,
    _MAGIC = 2
  },
  _BUFF_TYPE = {
    _addedDDType = 39,
    _hitType = 40,
    _DVType = 41,
    _HDVType = 42,
    _PVType = 43,
    _HPVType = 44
  },
  _totalStatList = {},
  _defaultDescSizeY = 0,
  _INDEX_DD = 1,
  _INDEX_ADD = 2,
  _INDEX_HIT = 3,
  _INDEX_DDV = 4,
  _INDEX_DPV = 5,
  _INDEX_RDV = 6,
  _INDEX_RPV = 7,
  _INDEX_MDV = 8,
  _INDEX_MPV = 9,
  _INDEX_REDUCE = 10,
  _INDEX_SHYSTAT1 = 11,
  _INDEX_SHYSTAT2 = 12,
  _INDEX_SHYSTAT3 = 13,
  _INDEX_HIT_RATE = 14,
  _INDEX_DDV_RATE = 15,
  _INDEX_RDV_RATE = 16,
  _INDEX_MDV_RATE = 17,
  _INDEX_COUNT = 18,
  _PERCENT_TO_RATIO = 1000000,
  _bgSize = 0,
  _statBGSize = 0,
  _descPosY = 0,
  _aDDPosY = 0,
  _hitPosY = 0,
  _hitRatePosY = 0,
  _initialize = false
}
runLua("UI_Data/Script/Widget/ToolTip/Panel_Window_Stat_All_1.lua")
runLua("UI_Data/Script/Widget/ToolTip/Panel_Window_Stat_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_WindowStatAllInit")
function FromClient_WindowStatAllInit()
  PaGlobal_Window_Stat_All:initialize()
end
