function PaGlobal_WorldMapNodeTooltip_VillageWar_Open(nodeBtn, isConsole)
  PaGlobal_WorldMapNodeTooltip_VillageWar:prepareOpen(nodeBtn, isConsole)
end
function PaGlobal_WorldMapNodeTooltip_VillageWar_Close()
  PaGlobal_WorldMapNodeTooltip_VillageWar:prepareClose()
end
