PaGlobal_SimpleInventory = {
  _ui = {
    _titleBar = UI.getChildControl(Panel_Window_SimpleInventory, "StaticText_Title"),
    _invenBG = UI.getChildControl(Panel_Window_SimpleInventory, "Static_Group_Inven"),
    _equipBG = UI.getChildControl(Panel_Window_SimpleInventory, "Static_Group_Equip"),
    _characterBG = UI.getChildControl(Panel_Window_SimpleInventory, "Static_SelectCharacter"),
    _keyguideBg = UI.getChildControl(Panel_Window_SimpleInventory, "Static_Key_GuideGroup_ConsoleUI")
  },
  _slotConfig = {
    createIcon = true,
    createBorder = true,
    createEnchant = true,
    createCount = true,
    createDuplicatedForDuel = true,
    createOriginalForDuel = true
  },
  _equipSlotConfig = {
    createIcon = false,
    createBorder = true,
    createCount = true,
    createCash = true,
    createBlack = true,
    createEnchant = true,
    createDuplicatedForDuel = true,
    createOriginalForDuel = true
  },
  _slotNoId = {
    [0] = "Static_Slot_RightHand",
    [1] = "Static_Slot_LeftHand",
    [2] = "Static_Slot_Gather",
    [3] = "Static_Slot_Chest",
    [4] = "Static_Slot_Glove",
    [5] = "Static_Slot_Boots",
    [6] = "Static_Slot_Helm",
    [7] = "Static_Slot_Necklace",
    [8] = "Static_Slot_Ring1",
    [9] = "Static_Slot_Ring2",
    [10] = "Static_Slot_Earing1",
    [11] = "Static_Slot_Earing2",
    [12] = "Static_Slot_Belt",
    [13] = "Static_Slot_Lantern",
    [14] = "Static_Slot_Avatar_Chest",
    [15] = "Static_Slot_Avatar_Gloves",
    [16] = "Static_Slot_Avatar_Boots",
    [17] = "Static_Slot_Avatar_Helm",
    [18] = "Static_Slot_Avatar_RightHand",
    [19] = "Static_Slot_Avatar_LeftHand",
    [20] = "Static_Slot_Avatar_UnderWear",
    [22] = "Static_Slot_FaceDecoration1",
    [23] = "Static_Slot_FaceDecoration2",
    [21] = "Static_Slot_FaceDecoration3",
    [27] = "Static_Slot_AlchemyStone",
    [29] = "Static_Slot_AwakenWeapon",
    [30] = "Static_Slot_Avatar_AwakenWeapon",
    [31] = "Static_Slot_QuestBook"
  },
  _slotNoIdToString = {
    [__eEquipSlotNoRightHand] = PAGetString(Defines.StringSheet_GAME, "PANEL_TOOLTIP_EQUIP_MAINHAND"),
    [__eEquipSlotNoLeftHand] = PAGetString(Defines.StringSheet_GAME, "PANEL_TOOLTIP_EQUIP_SUBHAND"),
    [__eEquipSlotNoSubTool] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_GATHERTOOLS"),
    [__eEquipSlotNoChest] = PAGetString(Defines.StringSheet_GAME, "PANEL_TOOLTIP_EQUIP_UPPERBODY"),
    [__eEquipSlotNoGlove] = PAGetString(Defines.StringSheet_GAME, "PANEL_TOOLTIP_EQUIP_GLOVES"),
    [__eEquipSlotNoBoots] = PAGetString(Defines.StringSheet_GAME, "PANEL_TOOLTIP_EQUIP_BOOTS"),
    [__eEquipSlotNoHelm] = PAGetString(Defines.StringSheet_GAME, "PANEL_TOOLTIP_EQUIP_HELM"),
    [__eEquipSlotNoNecklace] = PAGetString(Defines.StringSheet_GAME, "PANEL_TOOLTIP_EQUIP_NECKLACE"),
    [__eEquipSlotNoRing1] = PAGetString(Defines.StringSheet_GAME, "PANEL_TOOLTIP_EQUIP_RING"),
    [__eEquipSlotNoRing2] = PAGetString(Defines.StringSheet_GAME, "PANEL_TOOLTIP_EQUIP_RING"),
    [__eEquipSlotNoEaring1] = PAGetString(Defines.StringSheet_GAME, "PANEL_TOOLTIP_EQUIP_EARRING"),
    [__eEquipSlotNoEaring2] = PAGetString(Defines.StringSheet_GAME, "PANEL_TOOLTIP_EQUIP_EARRING"),
    [__eEquipSlotNoBelt] = PAGetString(Defines.StringSheet_GAME, "PANEL_TOOLTIP_EQUIP_WAISTBAND"),
    [__eEquipSlotNoLantern] = PAGetString(Defines.StringSheet_GAME, "PANEL_TOOLTIP_EQUIP_LANTERN"),
    [__eEquipSlotNoAvatarChest] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_BODY"),
    [__eEquipSlotNoAvatarGlove] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_HANDS"),
    [__eEquipSlotNoAvatarBoots] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_BOOTS"),
    [__eEquipSlotNoAvatarHelm] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_HELM"),
    [__eEquipSlotNoAvatarWeapon] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_MAIN"),
    [__eEquipSlotNoAvatarSubWeapon] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_SUB"),
    [__eEquipSlotNoAvatarUnderwear] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_UNDERWEAR"),
    [__eEquipSlotNoFaceDecoration1] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_HEAD"),
    [__eEquipSlotNoFaceDecoration2] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_EYES"),
    [__eEquipSlotNoFaceDecoration3] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_AVATAR_MOUSE"),
    [__eEquipSlotNoAlchemyStone] = PAGetString(Defines.StringSheet_GAME, "Lua_EquipSlotNo_String_alchemyStone"),
    [__eEquipSlotNoAwakenWeapon] = PAGetString(Defines.StringSheet_GAME, "Lua_EquipSlotNo_String_awakenWeapon"),
    [__eEquipSlotNoAvatarAwakenWeapon] = PAGetString(Defines.StringSheet_GAME, "Lua_EquipSlotNo_String_avatarAwakenWeapon"),
    [__eEquipSlotNoQuestBook] = PAGetString(Defines.StringSheet_GAME, "LUA_EQUIPMENT_QUESTBOOK")
  },
  _config = {
    _slotCount = 64,
    _inventoryMax = 192,
    _slotCols = 8,
    _slotRows = 8,
    _initPosX = 10,
    _initPosY = 10
  },
  _itemWhereType = CppEnums.ItemWhereType.eInventory,
  _invenWrapper = nil,
  _currentIndex = 0,
  _currentItemCount = 0,
  _slots = Array.new(),
  _sortedItemList = Array.new(),
  _selectedTab = 0,
  _maxTabCount = 2,
  _EquipNoMin = CppEnums.EquipSlotNo.rightHand,
  _EquipNoMax = CppEnums.EquipSlotNo.equipSlotNoCount,
  _UnUsedEquipNo_01 = 100,
  _UnUsedEquipNo_02 = 101,
  _equipSlotBG = {},
  _equipSlot = {},
  _extendedSlotInfoArray = nil,
  _equipWrapper = nil,
  _characterDataCount = 0,
  _currentCharacterNo = nil,
  _currentCharacterIndex = -1,
  _selectedCharacterNo = nil,
  _selectedCharacterIndex = 0,
  _selectedCharacterClassType = __eClassType_Count,
  _selectedCharacterEquipAwakenWeapon = false,
  _originUnderWearSpanX = 0,
  _changeUnderWearSpanX = 0,
  _originPanelSizeX = 0,
  _searchItemSlotList = {},
  _searchItemEquipSlotList = {},
  _isConsole = false
}
function FromClient_SimpleInventoryInit()
  local self = PaGlobal_SimpleInventory
  self:init()
end
runLua("UI_Data/Script/Window/Inventory/Panel_Window_SimpleInventory_1.lua")
runLua("UI_Data/Script/Window/Inventory/Panel_Window_SimpleInventory_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_SimpleInventoryInit")
